=== ld112501/APLICACIONESWEB/TALLERES/TERCER CORTE/XMLSCHEMA - DTD/XML/src/DTD.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT CURSOS (SEMESTRE, ESTUDIANTE, MATERIA, DOCENTE)>
<!ELEMENT SEMESTEE (#PCDATA)>
<!ELEMENT ESTUDIANTE (CODIGO_EST,NOMBRE_EST,APELLIDO_EST,CEDULA_EST)>
<!ELEMENT CODIGO_EST (#PCDATA)>
<!ELEMENT NOMBRE_EST (#PCDATA)>
<!ELEMENT APELLIDO_EST (#PCDATA)>
<!ELEMENT CEDULA_EST (#PCDATA)>
<!ELEMENT MATERIA (CODIGO_MAT,NOMBRE_MAT,DESCRIPCION_MAT,CREDITOS_MAT)>
<!ELEMENT CODIGO_MA (#PCDATA)>
<!ELEMENT NOMBRE_MAT (#PCDATA)>
<!ELEMENT DESCRIPCION_MAT (#PCDATA)>
<!ELEMENT CREDITOS_MAT (#PCDATA)>
<!ELEMENT DOCENTE (CODIGO_DOC,NOMBRE_DOC,APELLIDO_DOC,CEDULA_DOC)>
<!ELEMENT CODIGO_DOC (#PCDATA)>
<!ELEMENT NOMBRE_DOC (#PCDATA)>
<!ELEMENT APELLIDO_DOC (#PCDATA)>
<!ELEMENT CEDULA_DOC (#PCDATA)>

=== ld112501/APLICACIONESWEB/TALLERES/TERCER CORTE/XMLSCHEMA - DTD/XML/src/DTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CURSOS SYSTEM "DTD.dtd" >
<CURSOS>
   <SEMESTRE>
  <SEMESTRE/>
  <ESTUDIANTE>
    <CODIGO_EST>CODIGO_EST</CODIGO_EST>
    <NOMBRE_EST>NOMBRE_EST</NOMBRE_EST>
    <APELLIDO_EST>APELLIDO_EST</APELLIDO_EST>
    <CEDULA_EST>CEDULA_EST</CEDULA_EST>
  </ESTUDIANTE>
  <MATERIA>
    <CODIGO_MAT/>
    <NOMBRE_MAT>NOMBRE_MAT</NOMBRE_MAT>
    <DESCRIPCION_MAT>DESCRIPCION_MAT</DESCRIPCION_MAT>
    <CREDITOS_MAT>CREDITOS_MAT</CREDITOS_MAT>
  </MATERIA>
  <DOCENTE>
    <CODIGO_DOC>CODIGO_DOC</CODIGO_DOC>
    <NOMBRE_DOC>NOMBRE_DOC</NOMBRE_DOC>
    <APELLIDO_DOC>APELLIDO_DOC</APELLIDO_DOC>
    <CEDULA_DOC>CEDULA_DOC</CEDULA_DOC>
  </DOCENTE>
</CURSOS>
